import { DNSProvider } from "@/utils/DNSProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DNSProvider>{children}</DNSProvider>
      </body>
    </html>
  );
}
